from __future__ import annotations

import csv
import json
from pathlib import Path

from airborne_vv.models import CampaignResult, Requirement


def write_evidence(
    campaign: CampaignResult,
    requirements: tuple[Requirement, ...],
    output_dir: Path,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    summary = {
        "schema_version": 1,
        "software_level": campaign.software_level,
        "campaign_passed": campaign.passed,
        "cases_total": len(campaign.results),
        "cases_passed": sum(result.passed for result in campaign.results),
        "requirements_total": len(campaign.requirement_ids),
        "requirements_covered": len(campaign.covered_requirement_ids),
        "requirements_coverage_percent": campaign.coverage_percent,
        "results": [result.as_dict() for result in campaign.results],
    }
    (output_dir / "verification-report.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    lines = [
        "# Verification Report",
        "",
        f"- Software level used for this educational exercise: {campaign.software_level}",
        f"- Campaign result: {'PASS' if campaign.passed else 'FAIL'}",
        f"- Cases: {summary['cases_passed']}/{summary['cases_total']} passed",
        (
            f"- Requirements: {summary['requirements_covered']}/"
            f"{summary['requirements_total']} covered"
        ),
        "",
        "| Case | Expected | Actual | Result |",
        "|---|---|---|---|",
    ]
    lines.extend(
        f"| {result.case_id} | {result.expected_state.value} | {result.actual_state.value} | "
        f"{'PASS' if result.passed else 'FAIL'} |"
        for result in campaign.results
    )
    lines.extend(
        [
            "",
            (
                "This evidence is generated by an unqualified educational tool and is not "
                "certification data."
            ),
            "",
        ]
    )
    (output_dir / "verification-report.md").write_text("\n".join(lines), encoding="utf-8")

    cases_by_requirement: dict[str, list[str]] = {
        requirement.requirement_id: [] for requirement in requirements
    }
    for result in campaign.results:
        for requirement_id in result.requirement_ids:
            cases_by_requirement[requirement_id].append(result.case_id)
    with (output_dir / "traceability.csv").open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(["requirement_id", "level", "verification_method", "case_ids"])
        for requirement in sorted(requirements, key=lambda item: item.requirement_id):
            writer.writerow(
                [
                    requirement.requirement_id,
                    requirement.level,
                    requirement.verification_method,
                    ";".join(sorted(cases_by_requirement[requirement.requirement_id])),
                ]
            )
